/**
 * Script to bundle TypeScript lib files as strings for the type checker.
 *
 * Run with: npx tsx scripts/bundle-ts-libs.ts
 *
 * This extracts lib.dom.d.ts, lib.es2022.d.ts, etc. from the typescript
 * package and generates a TypeScript module that exports them as strings.
 * This allows the TypeCheckService to provide DOM and ES types without
 * requiring filesystem access to node_modules at runtime.
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// TypeScript lib files needed for panel development
const LIBS = [
  "lib.es5.d.ts",
  "lib.es2015.core.d.ts",
  "lib.es2015.collection.d.ts",
  "lib.es2015.symbol.d.ts",
  "lib.es2015.symbol.wellknown.d.ts",
  "lib.es2015.iterable.d.ts",
  "lib.es2015.generator.d.ts",
  "lib.es2015.promise.d.ts",
  "lib.es2015.proxy.d.ts",
  "lib.es2015.reflect.d.ts",
  "lib.es2016.array.include.d.ts",
  "lib.es2016.intl.d.ts",
  "lib.es2017.object.d.ts",
  "lib.es2017.sharedmemory.d.ts",
  "lib.es2017.string.d.ts",
  "lib.es2017.intl.d.ts",
  "lib.es2017.typedarrays.d.ts",
  "lib.es2017.date.d.ts",
  "lib.es2018.asyncgenerator.d.ts",
  "lib.es2018.asynciterable.d.ts",
  "lib.es2018.intl.d.ts",
  "lib.es2018.promise.d.ts",
  "lib.es2018.regexp.d.ts",
  "lib.es2019.array.d.ts",
  "lib.es2019.object.d.ts",
  "lib.es2019.string.d.ts",
  "lib.es2019.symbol.d.ts",
  "lib.es2019.intl.d.ts",
  "lib.es2020.bigint.d.ts",
  "lib.es2020.date.d.ts",
  "lib.es2020.intl.d.ts",
  "lib.es2020.number.d.ts",
  "lib.es2020.promise.d.ts",
  "lib.es2020.sharedmemory.d.ts",
  "lib.es2020.string.d.ts",
  "lib.es2020.symbol.wellknown.d.ts",
  "lib.es2021.promise.d.ts",
  "lib.es2021.string.d.ts",
  "lib.es2021.weakref.d.ts",
  "lib.es2021.intl.d.ts",
  "lib.es2022.array.d.ts",
  "lib.es2022.error.d.ts",
  "lib.es2022.intl.d.ts",
  "lib.es2022.object.d.ts",
  "lib.es2022.regexp.d.ts",
  "lib.es2022.string.d.ts",
  "lib.dom.d.ts",
  "lib.dom.iterable.d.ts",
  "lib.dom.asynciterable.d.ts",
];

// Find TypeScript lib directory
function findTsLibPath(): string {
  // Try to find typescript in node_modules
  const candidates = [
    path.resolve(__dirname, "../node_modules/typescript/lib"),
    path.resolve(__dirname, "../../../node_modules/typescript/lib"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error(
    "Could not find TypeScript lib directory. Make sure typescript is installed."
  );
}

function sanitizeName(libName: string): string {
  // lib.es2022.d.ts → lib_es2022_d_ts
  return libName.replace(/[.-]/g, "_");
}

function main(): void {
  const tsLibPath = findTsLibPath();
  console.log(`Found TypeScript libs at: ${tsLibPath}`);

  const outputLines: string[] = [
    "/**",
    " * Bundled TypeScript lib files for the type checker.",
    " *",
    " * AUTO-GENERATED by scripts/bundle-ts-libs.ts",
    " * Do not edit manually.",
    " */",
    "",
  ];

  const exportedNames: string[] = [];
  let totalSize = 0;

  for (const lib of LIBS) {
    const libPath = path.join(tsLibPath, lib);

    if (!fs.existsSync(libPath)) {
      console.warn(`Warning: ${lib} not found, skipping`);
      continue;
    }

    const content = fs.readFileSync(libPath, "utf-8");
    const name = sanitizeName(lib);
    totalSize += content.length;

    outputLines.push(`export const ${name} = ${JSON.stringify(content)};`);
    outputLines.push("");
    exportedNames.push(name);

    console.log(`  Bundled ${lib} (${(content.length / 1024).toFixed(1)}KB)`);
  }

  // Add a combined map for easy access
  outputLines.push("/**");
  outputLines.push(" * Map of lib file names to their contents.");
  outputLines.push(" */");
  outputLines.push("export const TS_LIB_FILES: Record<string, string> = {");
  for (const lib of LIBS) {
    const name = sanitizeName(lib);
    if (exportedNames.includes(name)) {
      outputLines.push(`  "${lib}": ${name},`);
    }
  }
  outputLines.push("};");
  outputLines.push("");

  const outputPath = path.resolve(__dirname, "../src/typecheck/lib/typescript-libs.ts");
  fs.writeFileSync(outputPath, outputLines.join("\n"));

  console.log(`\nGenerated ${outputPath}`);
  console.log(`Total bundled size: ${(totalSize / 1024 / 1024).toFixed(2)}MB`);
  console.log(`Bundled ${exportedNames.length} lib files`);
}

main();
