// @generated by @natstack/shared/workspace/extensionRegistry — do not edit by hand.
//
// Type-only re-exports that pull each workspace extension's module into the
// type-check program so its `declare module "@natstack/extension"` registry
// augmentation is active. Re-exported from `./extensions.ts`, so any panel that
// imports `@workspace/runtime` can type-check `extensions.use("...")` against the
// full registry — the same set the repo-wide `tsc` sees via `include`.

export type { Api as Ext_workspace_extensions_browser_data } from "@workspace-extensions/browser-data";
export type { Api as Ext_workspace_extensions_file_tools } from "@workspace-extensions/file-tools";
export type { Api as Ext_workspace_extensions_image_service } from "@workspace-extensions/image-service";
export type { Api as Ext_workspace_extensions_react_native } from "@workspace-extensions/react-native";
export type { Api as Ext_workspace_extensions_shell } from "@workspace-extensions/shell";
