import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

export const workerRuntimeSurface: RuntimeSurface = {
  target: "workerRuntime",
  description: "Properties available on the object returned by createWorkerRuntime(env).",
  exports: {
    id: valueEntry(),
    rpc: valueEntry(),
    db: valueEntry(),
    fs: valueEntry(),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "setInitPanels",
      "switchTo",
    ]),
    oauth: namespaceEntry([
      "getToken",
      "getConnection",
      "listConnections",
      "listProviders",
      "connect",
      "requestConsent",
      "startAuth",
      "waitForConnection",
      "disconnect",
      "listConsents",
    ]),
    notifications: namespaceEntry(["show", "dismiss"]),
    contextId: valueEntry(),
    gitConfig: valueEntry(),
    pubsubConfig: valueEntry(),
    callMain: valueEntry(),
    getWorkspaceTree: valueEntry(),
    listBranches: valueEntry(),
    listCommits: valueEntry(),
    exposeMethod: valueEntry(),
    getParent: valueEntry(),
    handleRpcPost: valueEntry(),
    destroy: valueEntry(),
  },
};
