import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

export const workerRuntimeSurface: RuntimeSurface = {
  target: "workerRuntime",
  description: "Properties available on the object returned by createWorkerRuntime(env).",
  exports: {
    id: valueEntry(),
    rpc: valueEntry(),
    fs: valueEntry(),
    doTargetId: valueEntry("Build a unified RPC target ID for a Durable Object reference."),
    createDurableObjectServiceClient: valueEntry("Resolve a Durable Object-backed service and call it through unified RPC."),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "listServices",
      "resolveService",
      "resolveDurableObject",
      "durableObjectService",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "delete",
      "setInitPanels",
      "setConfigField",
      "switchTo",
      "units",
    ]),
    credentials: namespaceEntry([
      "store",
      "connect",
      "configureClient",
      "requestCredentialInput",
      "getClientConfigStatus",
      "deleteClientConfig",
      "listStoredCredentials",
      "revokeCredential",
      "grantCredential",
      "resolveCredential",
      "fetch",
      "hookForUrl",
      "gitHttp",
    ]),
    git: namespaceEntry([
      "http",
      "importProject",
      "completeWorkspaceDependencies",
      "setSharedRemote",
      "removeSharedRemote",
      "syncRepoToContexts",
      "client",
    ]),
    gad: namespaceEntry([
      "rawSql",
      "query",
      "status",
      "ensureBlob",
      "getTrajectoryBranchHead",
      "appendTrajectoryBatch",
      "listTrajectoryEvents",
      "appendChannelEnvelope",
      "getChannelEnvelope",
      "getTrajectoryForEnvelope",
      "listPublishedEnvelopesForTrajectory",
      "getEnvelopesForTrajectory",
      "getPublishedArtifactsForTurn",
      "getPrivateLineageForPublishedEnvelope",
      "getDownstreamConsumers",
      "getChannelReplayWindow",
      "listChannelEnvelopesAfter",
      "listChannelEnvelopesBefore",
      "getInitialChannelWindow",
      "listChannelEnvelopes",
      "listGadBranchFiles",
      "diffGadStates",
      "readGadFileAtState",
      "getGadStateProducer",
      "blameGadFileSnippet",
      "validateGadHashes",
      "clearDirtyAfterValidation",
      "checkGadIntegrity",
      "rebuildTrajectoryProjections",
    ]),
    webhooks: namespaceEntry([
      "createSubscription",
      "listSubscriptions",
      "revokeSubscription",
      "rotateSecret",
    ]),
    extensions: namespaceEntry([
      "use",
      "useWithStreams",
      "streamCall",
      "on",
      "list",
      "install",
      "uninstall",
      "setEnabled",
      "update",
      "reload",
    ]),
    approvals: namespaceEntry(["request", "revoke", "list"]),
    notifications: namespaceEntry(["show", "dismiss"]),
    contextId: valueEntry(),
    gatewayConfig: valueEntry("Gateway base URL and bearer token for NatStack service routes."),
    gatewayFetch: valueEntry("Fetch helper that prefixes gateway-relative paths and adds Authorization: Bearer."),
    gitConfig: valueEntry("Git HTTP endpoint and token derived from the gateway config."),
    callMain: valueEntry(),
    openExternal: valueEntry(),
    getWorkspaceTree: valueEntry(),
    listBranches: valueEntry(),
    listCommits: valueEntry(),
    requestApproval: valueEntry(),
    revokeApproval: valueEntry(),
    listApprovals: valueEntry(),
    exposeMethod: valueEntry(),
    getParent: valueEntry(),
    handleRpcPost: valueEntry(),
    destroy: valueEntry(),
  },
};
