import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

export const panelRuntimeSurface: RuntimeSurface = {
  target: "panel",
  description: "Top-level value exports available from @workspace/runtime in panel eval contexts.",
  exports: {
    Rpc: valueEntry("RPC helpers namespace export."),
    z: valueEntry("Zod export."),
    defineContract: valueEntry(),
    noopParent: valueEntry(),
    buildPanelLink: valueEntry(),
    parseContextId: valueEntry(),
    isValidContextId: valueEntry(),
    getInstanceId: valueEntry(),
    id: valueEntry(),
    rpc: valueEntry(),
    parent: valueEntry(),
    getParent: valueEntry(),
    getParentWithContract: valueEntry(),
    onConnectionError: valueEntry(),
    getInfo: valueEntry(),
    closeSelf: valueEntry(),
    focusPanel: valueEntry(),
    getWorkspaceTree: valueEntry(),
    listBranches: valueEntry(),
    listCommits: valueEntry(),
    getTheme: valueEntry(),
    onThemeChange: valueEntry(),
    onFocus: valueEntry(),
    exposeMethod: valueEntry(),
    contextId: valueEntry(),
    recoveryCoordinator: valueEntry("Panel transport recovery phase coordinator."),
    parentId: valueEntry(),
    fs: valueEntry(),
    createGatewayFetch: valueEntry("Create a gateway-authenticated fetch helper from an explicit config."),
    gatewayConfig: valueEntry("Gateway base URL and bearer token for NatStack service routes."),
    gatewayFetch: valueEntry("Fetch helper that prefixes gateway-relative paths and adds Authorization: Bearer."),
    gitConfig: valueEntry("Git HTTP endpoint and token derived from the gateway config."),
    pubsubConfig: valueEntry("PubSub WebSocket endpoint and token derived from the gateway config."),
    env: valueEntry(),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "listServices",
      "resolveService",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    normalizePath: valueEntry(),
    getFileName: valueEntry(),
    resolvePath: valueEntry(),
    getStateArgs: valueEntry(),
    useStateArgs: valueEntry(),
    setStateArgs: valueEntry(),
    createBrowserPanel: valueEntry(),
    openExternal: valueEntry(),
    onChildCreated: valueEntry(),
    getBrowserHandle: valueEntry(),
    openPanel: valueEntry(),
    adblock: namespaceEntry([
      "getStats",
      "isActive",
      "getStatsForPanel",
      "isEnabledForPanel",
      "setEnabledForPanel",
      "resetStatsForPanel",
      "getPanelUrl",
      "addToWhitelist",
      "removeFromWhitelist",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "delete",
      "setInitPanels",
      "setConfigField",
      "switchTo",
      "openPanel",
      "units",
    ]),
    credentials: namespaceEntry([
      "store",
      "connect",
      "configureClient",
      "requestCredentialInput",
      "getClientConfigStatus",
      "deleteClientConfig",
      "listStoredCredentials",
      "revokeCredential",
      "grantCredential",
      "resolveCredential",
      "fetch",
      "hookForUrl",
      "gitHttp",
    ]),
    git: namespaceEntry([
      "http",
      "importProject",
      "completeWorkspaceDependencies",
      "setSharedRemote",
      "removeSharedRemote",
      "client",
    ]),
    gad: namespaceEntry([
      "rawSql",
      "query",
      "status",
      "ensureBlob",
      "ensureGadBranch",
      "getGadBranchHead",
      "appendGadTrajectoryBatch",
      "materializePiMessages",
      "listGadBranchTrajectory",
      "listGadBranchToolCalls",
      "forkGadBranch",
      "listGadBranches",
      "listGadBranchFiles",
      "diffGadStates",
      "readGadFileAtState",
      "getGadToolProvenance",
      "getGadStateProducer",
      "blameGadFileSnippet",
      "enqueueGadIndexJob",
      "processGadIndexJobs",
      "validateGadHashes",
      "clearDirtyAfterValidation",
      "checkGadIntegrity",
      "revokeRawSqlWriteApproval",
    ]),
    webhooks: namespaceEntry([
      "createSubscription",
      "listSubscriptions",
      "revokeSubscription",
      "rotateSecret",
    ]),
    extensions: namespaceEntry([
      "use",
      "on",
      "list",
      "install",
      "uninstall",
      "setEnabled",
      "update",
      "reload",
    ]),
    requestApproval: valueEntry(),
    revokeApproval: valueEntry(),
    listApprovals: valueEntry(),
    notifications: namespaceEntry(["show", "dismiss"]),
  },
};
