import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

export const workerRuntimeSurface: RuntimeSurface = {
  target: "workerRuntime",
  description: "Properties available on the object returned by createWorkerRuntime(env).",
  exports: {
    id: valueEntry(),
    rpc: valueEntry(),
    fs: valueEntry(),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "listServices",
      "resolveService",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "setInitPanels",
      "switchTo",
      "units",
    ]),
    credentials: namespaceEntry([
      "store",
      "connect",
      "configureClient",
      "requestCredentialInput",
      "getClientConfigStatus",
      "deleteClientConfig",
      "listStoredCredentials",
      "revokeCredential",
      "grantCredential",
      "resolveCredential",
      "fetch",
      "hookForUrl",
      "gitHttp",
    ]),
    git: namespaceEntry([
      "http",
      "importProject",
      "completeWorkspaceDependencies",
      "setSharedRemote",
      "removeSharedRemote",
      "client",
    ]),
    gad: namespaceEntry([
      "rawSql",
      "query",
      "status",
      "ensureBlob",
      "ensureBranch",
      "recordSession",
      "endSession",
      "recordTurn",
      "beginToolCall",
      "completeToolCall",
      "recordRead",
      "recordMutation",
      "listBranches",
      "getBranch",
      "listBranchFiles",
      "forkBranch",
      "createBranchSnapshot",
      "listBranchSnapshots",
      "recordPlan",
      "supersedePlan",
      "listPlans",
      "getPlanChain",
      "createChunk",
      "addChunkMention",
      "relateChunk",
      "listChunks",
      "getChunkMentions",
      "getChunksFor",
      "getRelationsFor",
      "walkDependencies",
      "upsertChunkEmbedding",
      "upsertTurnEmbedding",
      "findSimilarChunks",
      "findSimilarTurns",
      "parseFileVersion",
      "getStructures",
      "findParsedByName",
      "getStructuresInRange",
      "getSupportedLanguages",
      "indexTurn",
      "indexFileVersion",
      "indexSession",
      "getReviewContext",
      "setBlobPolicy",
      "getBlobPolicy",
      "redactBlob",
      "listBlobReferences",
      "revokeRawSqlWriteApproval",
    ]),
    webhooks: namespaceEntry([
      "createSubscription",
      "listSubscriptions",
      "revokeSubscription",
      "rotateSecret",
    ]),
    extensions: namespaceEntry([
      "use",
      "on",
      "list",
      "install",
      "uninstall",
      "setEnabled",
      "update",
      "reload",
    ]),
    notifications: namespaceEntry(["show", "dismiss"]),
    contextId: valueEntry(),
    gatewayConfig: valueEntry("Gateway base URL and bearer token for NatStack service routes."),
    gatewayFetch: valueEntry("Fetch helper that prefixes gateway-relative paths and adds Authorization: Bearer."),
    gitConfig: valueEntry("Git HTTP endpoint and token derived from the gateway config."),
    pubsubConfig: valueEntry("Always null in worker runtime; PubSub access goes through service routes."),
    callMain: valueEntry(),
    openExternal: valueEntry(),
    getWorkspaceTree: valueEntry(),
    listBranches: valueEntry(),
    listCommits: valueEntry(),
    requestApproval: valueEntry(),
    revokeApproval: valueEntry(),
    listApprovals: valueEntry(),
    exposeMethod: valueEntry(),
    getParent: valueEntry(),
    handleRpcPost: valueEntry(),
    destroy: valueEntry(),
  },
};
