import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

const panelTreeDescription =
  "Return signatures: self(): PanelHandle; get(id): PanelHandle; list(): Promise<PanelHandle[]>; roots(): Promise<PanelHandle[]>; children(id): Promise<PanelHandle[]>; parent(id): PanelHandle | null; open(source, opts?): Promise<PanelHandle>. `self()` and `get()` are synchronous handle factories; catch errors on async handle methods like `refresh()` or `getInfo()`.";

export const panelRuntimeSurface: RuntimeSurface = {
  target: "panel",
  description: "Top-level value exports available from @workspace/runtime in panel eval contexts.",
  exports: {
    Rpc: valueEntry("RPC helpers namespace export."),
    z: valueEntry("Zod export."),
    defineContract: valueEntry(),
    buildPanelLink: valueEntry(),
    parseContextId: valueEntry(),
    isValidContextId: valueEntry(),
    getInstanceId: valueEntry(),
    id: valueEntry(),
    entityId: valueEntry("Panel entity id (panel:<historyEntryKey>) — same as `id`."),
    slotId: valueEntry("Stable panel slot id for panel tree operations."),
    rpc: valueEntry(),
    parent: valueEntry(),
    getParent: valueEntry(),
    getParentWithContract: valueEntry(),
    onConnectionError: valueEntry(),
    getInfo: valueEntry(),
    focusPanel: valueEntry(),
    getWorkspaceTree: valueEntry(),
    listBranches: valueEntry(),
    listCommits: valueEntry(),
    getTheme: valueEntry(),
    onThemeChange: valueEntry(),
    onFocus: valueEntry(),
    expose: valueEntry(),
    contextId: valueEntry(),
    recoveryCoordinator: valueEntry("Panel transport recovery phase coordinator."),
    parentId: valueEntry(),
    fs: valueEntry(),
    createGatewayFetch: valueEntry(
      "Create a gateway-authenticated fetch helper from an explicit config."
    ),
    gatewayConfig: valueEntry("Gateway base URL and bearer token for NatStack service routes."),
    gatewayFetch: valueEntry(
      "Fetch helper that prefixes gateway-relative paths and adds Authorization: Bearer."
    ),
    gitConfig: valueEntry("Git HTTP endpoint and token derived from the gateway config."),
    env: valueEntry(),
    doTargetId: valueEntry("Build a unified RPC target ID for a Durable Object reference."),
    createDurableObjectServiceClient: valueEntry(
      "Resolve a Durable Object-backed service and call it through unified RPC."
    ),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "listServices",
      "resolveService",
      "resolveDurableObject",
      "durableObjectService",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    normalizePath: valueEntry(),
    getFileName: valueEntry(),
    resolvePath: valueEntry(),
    getStateArgs: valueEntry(),
    useStateArgs: valueEntry(),
    setStateArgs: valueEntry(),
    setStateArgsForPanel: valueEntry(),
    openExternal: valueEntry(),
    onChildCreated: valueEntry(),
    openPanel: valueEntry(),
    listPanels: valueEntry(),
    getPanelHandle: valueEntry(),
    panelTree: namespaceEntry(
      ["self", "get", "list", "roots", "children", "parent", "open"],
      panelTreeDescription
    ),
    agentApi: valueEntry(),
    Journal: valueEntry(),
    withJournal: valueEntry(),
    currentJournal: valueEntry(),
    adblock: namespaceEntry([
      "getStats",
      "isActive",
      "getStatsForPanel",
      "isEnabledForPanel",
      "setEnabledForPanel",
      "resetStatsForPanel",
      "getPanelUrl",
      "addToWhitelist",
      "removeFromWhitelist",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "delete",
      "setInitPanels",
      "setConfigField",
      "switchTo",
      "openPanel",
      "units",
    ]),
    credentials: namespaceEntry([
      "store",
      "connect",
      "configureClient",
      "requestCredentialInput",
      "getClientConfigStatus",
      "deleteClientConfig",
      "listStoredCredentials",
      "revokeCredential",
      "grantCredential",
      "resolveCredential",
      "fetch",
      "hookForUrl",
      "gitHttp",
    ]),
    git: namespaceEntry([
      "http",
      "importProject",
      "completeWorkspaceDependencies",
      "setSharedRemote",
      "removeSharedRemote",
      "ensureRepoPresentInContexts",
      "publishWorkspaceRepo",
      "client",
    ]),
    gad: namespaceEntry([
      "rawSql",
      "query",
      "status",
      "ensureBlob",
      "getTrajectoryBranchHead",
      "appendTrajectoryBatch",
      "listTrajectoryEvents",
      "appendChannelEnvelope",
      "getChannelEnvelope",
      "getTrajectoryForEnvelope",
      "listPublishedEnvelopesForTrajectory",
      "getEnvelopesForTrajectory",
      "getPublishedArtifactsForTurn",
      "getPrivateLineageForPublishedEnvelope",
      "getDownstreamConsumers",
      "getChannelReplayWindow",
      "listChannelEnvelopesAfter",
      "listChannelEnvelopesBefore",
      "getInitialChannelWindow",
      "listChannelEnvelopes",
      "inspectChannelEnvelopes",
      "listStoredValueRefs",
      "inspectStorageDiagnostics",
      "listGadBranchFiles",
      "diffGadStates",
      "readGadFileAtState",
      "getGadStateProducer",
      "blameGadFileSnippet",
      "validateGadHashes",
      "clearDirtyAfterValidation",
      "checkGadIntegrity",
      "rebuildTrajectoryProjections",
    ]),
    webhooks: namespaceEntry([
      "createSubscription",
      "listSubscriptions",
      "revokeSubscription",
      "rotateSecret",
    ]),
    extensions: namespaceEntry(["use", "on", "list", "reload"]),
    approvals: namespaceEntry(["request", "revoke", "list"]),
    requestApproval: valueEntry(),
    revokeApproval: valueEntry(),
    listApprovals: valueEntry(),
    notifications: namespaceEntry(["show", "dismiss"]),
  },
};
