import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

export const panelRuntimeSurface: RuntimeSurface = {
  target: "panel",
  description: "Top-level value exports available from @workspace/runtime in panel eval contexts.",
  exports: {
    Rpc: valueEntry("RPC helpers namespace export."),
    z: valueEntry("Zod export."),
    defineContract: valueEntry(),
    noopParent: valueEntry(),
    buildPanelLink: valueEntry(),
    parseContextId: valueEntry(),
    isValidContextId: valueEntry(),
    getInstanceId: valueEntry(),
    id: valueEntry(),
    rpc: valueEntry(),
    db: valueEntry(),
    parent: valueEntry(),
    getParent: valueEntry(),
    getParentWithContract: valueEntry(),
    onConnectionError: valueEntry(),
    getInfo: valueEntry(),
    closeSelf: valueEntry(),
    focusPanel: valueEntry(),
    getWorkspaceTree: valueEntry(),
    listBranches: valueEntry(),
    listCommits: valueEntry(),
    getTheme: valueEntry(),
    onThemeChange: valueEntry(),
    onFocus: valueEntry(),
    exposeMethod: valueEntry(),
    contextId: valueEntry(),
    parentId: valueEntry(),
    fs: valueEntry(),
    gitConfig: valueEntry(),
    pubsubConfig: valueEntry(),
    env: valueEntry(),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    normalizePath: valueEntry(),
    getFileName: valueEntry(),
    resolvePath: valueEntry(),
    getStateArgs: valueEntry(),
    useStateArgs: valueEntry(),
    setStateArgs: valueEntry(),
    createBrowserPanel: valueEntry(),
    openExternal: valueEntry(),
    onChildCreated: valueEntry(),
    getBrowserHandle: valueEntry(),
    openPanel: valueEntry(),
    oauth: namespaceEntry([
      "createLoopbackCallback",
    ]),
    adblock: namespaceEntry([
      "getStats",
      "isActive",
      "getStatsForPanel",
      "isEnabledForPanel",
      "setEnabledForPanel",
      "resetStatsForPanel",
      "getPanelUrl",
      "addToWhitelist",
      "removeFromWhitelist",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "setInitPanels",
      "switchTo",
      "openPanel",
    ]),
    credentials: namespaceEntry([
      "store",
      "beginCreateWithOAuthPkce",
      "beginCreateWithOAuthClientPkce",
      "completeCreateWithOAuthPkce",
      "connectWithOAuthPkce",
      "connectWithOAuthClientPkce",
      "requestOAuthClientConfig",
      "requestCredentialInput",
      "getOAuthClientConfigStatus",
      "listStoredCredentials",
      "revokeCredential",
      "grantCredential",
      "resolveCredential",
      "fetch",
      "hookForUrl",
      "gitHttp",
    ]),
    git: namespaceEntry([
      "http",
      "importProject",
      "completeWorkspaceDependencies",
      "setSharedRemote",
      "removeSharedRemote",
      "client",
    ]),
    webhooks: namespaceEntry([
      "createSubscription",
      "listSubscriptions",
      "revokeSubscription",
      "rotateSecret",
    ]),
    notifications: namespaceEntry(["show", "dismiss"]),
  },
};
