/**
 * Generates the `@workspace/runtime` extension-registry barrel.
 *
 * Extensions augment a global type registry: each extension's `index.ts`
 * declares `interface WorkspaceExtensions { "@scope/name": Api }` via
 * `declare module "@natstack/extension"`. That augmentation is only active in a
 * TypeScript program that actually contains the extension's `index.ts`. The
 * repo-wide `tsc` gets this for free through `include: workspace/**`, but
 * scoped programs (the per-panel typecheck service, Monaco) only contain a
 * panel plus what it imports — and a panel calls `extensions.use("...")` with a
 * string, never importing the extension. So the registry comes up empty.
 *
 * The barrel closes that gap through ordinary imports rather than per-surface
 * special-casing: it type-only re-exports each extension's `Api`, which pulls
 * the extension module into the program (activating its augmentation). It is
 * re-exported from `shared/extensions.ts`, which every panel reaches by
 * importing `@workspace/runtime` — so the registry propagates exactly like any
 * other type. The set mirrors `include: workspace/**` (every extension package
 * present in the workspace), keeping all type-check surfaces consistent.
 */

import * as fs from "fs";
import * as path from "path";

/** Location of the generated barrel within a workspace source tree. */
export const EXTENSION_REGISTRY_RELATIVE_PATH = path.join(
  "packages",
  "runtime",
  "src",
  "shared",
  "extensions-registry.ts",
);

interface ExtensionManifest {
  name?: string;
  natstack?: { extension?: unknown; entry?: unknown };
}

/** Matches an extension's `declare module "@natstack/extension" { ... }` block. */
const REGISTRY_AUGMENTATION = /declare\s+module\s+["']@natstack\/extension["']/;

function aliasFor(packageName: string): string {
  return "Ext_" + packageName.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function isExtensionManifest(pkg: ExtensionManifest | null): pkg is ExtensionManifest & { name: string } {
  return Boolean(
    pkg?.name &&
      pkg.natstack &&
      typeof pkg.natstack === "object" &&
      "extension" in pkg.natstack,
  );
}

function readManifest(dir: string): ExtensionManifest | null {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf-8")) as ExtensionManifest;
  } catch {
    return null;
  }
}

/**
 * Whether an extension opts into the typed registry by augmenting
 * `WorkspaceExtensions` in its entry file. This is the same declaration the
 * repo-wide `tsc` reads via `include`, so gating the barrel on it keeps every
 * surface's registry identical. Infra extensions that don't self-register (e.g.
 * typecheck-service) are excluded, so their type graph never enters panels.
 */
function selfRegisters(dir: string, manifest: ExtensionManifest): boolean {
  const entry = typeof manifest.natstack?.entry === "string" ? manifest.natstack.entry : "index.ts";
  try {
    return REGISTRY_AUGMENTATION.test(fs.readFileSync(path.join(dir, entry), "utf-8"));
  } catch {
    return false;
  }
}

/**
 * Names of every extension package under `<workspacePath>/extensions/*` that
 * registers itself in the `WorkspaceExtensions` type registry.
 */
export function discoverExtensionPackageNames(workspacePath: string): string[] {
  const root = path.join(workspacePath, "extensions");
  const names: string[] = [];
  const consider = (dir: string): void => {
    const pkg = readManifest(dir);
    if (isExtensionManifest(pkg) && selfRegisters(dir, pkg)) names.push(pkg.name);
  };

  let top: fs.Dirent[];
  try {
    top = fs.readdirSync(root, { withFileTypes: true });
  } catch {
    return [];
  }
  for (const entry of top) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith(".")) continue;
    const dir = path.join(root, entry.name);
    consider(dir);
  }
  return names;
}

/** Render the barrel contents for a set of extension package names. */
export function renderExtensionRegistry(packageNames: Iterable<string>): string {
  const sorted = [...new Set(packageNames)].sort();
  const header =
    "// @generated by @natstack/shared/workspace/extensionRegistry — do not edit by hand.\n" +
    "//\n" +
    "// Type-only re-exports that pull each workspace extension's module into the\n" +
    '// type-check program so its `declare module "@natstack/extension"` registry\n' +
    "// augmentation is active. Re-exported from `./extensions.ts`, so any panel that\n" +
    '// imports `@workspace/runtime` can type-check `extensions.use("...")` against the\n' +
    "// full registry — the same set the repo-wide `tsc` sees via `include`.\n\n";
  if (sorted.length === 0) {
    return header + "export {};\n";
  }
  return (
    header +
    sorted.map((name) => `export type { Api as ${aliasFor(name)} } from "${name}";`).join("\n") +
    "\n"
  );
}

/**
 * Regenerate the registry barrel for a workspace. Returns whether the file
 * changed. No-op (returns false) when the workspace has no runtime package.
 */
export function writeExtensionRegistry(workspacePath: string): boolean {
  const barrelPath = path.join(workspacePath, EXTENSION_REGISTRY_RELATIVE_PATH);
  if (!fs.existsSync(path.dirname(barrelPath))) return false;

  const content = renderExtensionRegistry(discoverExtensionPackageNames(workspacePath));
  let existing: string | null = null;
  try {
    existing = fs.readFileSync(barrelPath, "utf-8");
  } catch {
    /* file does not exist yet */
  }
  if (existing === content) return false;
  fs.writeFileSync(barrelPath, content);
  return true;
}
