export type {
  BrowserName,
  BrowserFamily,
  DetectedBrowser,
  DetectedProfile,
  ImportedBookmark,
  ImportedHistoryEntry,
  ImportedHistoryVisit,
  ImportHistoryBatchMeta,
  ImportBatchMeta,
  ImportedCookie,
  ImportedPassword,
  ImportedAutofillEntry,
  ImportedSearchEngine,
  ImportedExtension,
  ImportedPermission,
  ImportedSettings,
  ImportedFavicon,
  ImportedOpenTab,
  BrowserOpenTabsRequest,
  OpenTabsAsPanelsResult,
  ImportDataType,
  ImportRequest,
  ImportProgress,
  ImportResult,
  HistoryQuery,
  RecordHistoryVisitRequest,
  UpdateHistoryTitleRequest,
  HistoryAutocompleteQuery,
  CryptoProvider,
  BrowserDataReader,
  BookmarkExportFormat,
  PasswordExportFormat,
  CookieExportFormat,
  HistoryTransition,
  HistoryVisitSource,
  SameSiteValue,
  SourceScheme,
  ImportPhase,
} from "./types.js";

export {
  BrowserNameSchema,
  BrowserFamilySchema,
  DetectedBrowserSchema,
  DetectedProfileSchema,
  BrowserOpenTabsRequestSchema,
  ImportDataTypeSchema,
  ImportRequestSchema,
  HistoryQuerySchema,
  RecordHistoryVisitSchema,
  UpdateHistoryTitleSchema,
  HistoryAutocompleteQuerySchema,
  BookmarkSchema,
  PasswordSchema,
  BROWSER_NAMES,
  BROWSER_FAMILIES,
  HISTORY_VISIT_SOURCES,
  IMPORT_DATA_TYPES,
  resolveProfilePath,
} from "./types.js";

export { BrowserDataError } from "./errors.js";
export type { BrowserDataErrorCode } from "./errors.js";

export { createBrowserDataRpcClient } from "./client/browserDataRpcClient.js";
export type { BrowserDataClient } from "./client/browserDataRpcClient.js";
export { BROWSER_DATA_SCHEMA } from "./storage/index.js";
export type {
  StoredBookmark,
  StoredHistory,
  StoredVisit,
  StoredPassword,
  StoredCookie,
  StoredAutofill,
  StoredSearchEngine,
  StoredFavicon,
  StoredPermission,
  StoredImportRun,
  StoredImportRunSummary,
  StoredImportRunWithSummaries,
  ImportRunInput,
  ImportRunSummaryInput,
} from "./storage/index.js";
