import type { RuntimeSurface } from "./runtimeSurface.js";
import { namespaceEntry, valueEntry } from "./runtimeSurface.js";

const panelTreeDescription =
  "Runtime property, not workspace.panelTree. Signatures: self(): PanelHandle; get(id): PanelHandle; list(): Promise<PanelHandle[]>; roots(): Promise<PanelHandle[]>; children(id): Promise<PanelHandle[]>; parent(id): PanelHandle | null; navigate(id, source, opts?): Promise<{ id, title }>; open(source, opts?): Promise<PanelHandle>. Use list/roots/children/get for existing panels; navigate replaces an existing panel slot; open creates a new panel. self/get are sync; async methods refresh metadata as needed.";

export const workerRuntimeSurface: RuntimeSurface = {
  target: "workerRuntime",
  description: "Properties available on the object returned by createWorkerRuntime(env).",
  exports: {
    id: valueEntry(),
    rpc: valueEntry(),
    fs: valueEntry(),
    doTargetId: valueEntry("Build a unified RPC target ID for a Durable Object reference."),
    createDurableObjectServiceClient: valueEntry(
      "Resolve a Durable Object-backed service and call it through unified RPC."
    ),
    workers: namespaceEntry([
      "create",
      "destroy",
      "update",
      "list",
      "status",
      "listInstanceSources",
      "listServices",
      "resolveService",
      "resolveDurableObject",
      "durableObjectService",
      "getPort",
      "restartAll",
      "cloneDO",
      "destroyDO",
    ]),
    workspace: namespaceEntry([
      "list",
      "getActive",
      "getActiveEntry",
      "getConfig",
      "create",
      "delete",
      "setInitPanels",
      "setConfigField",
      "switchTo",
      "sourceTree",
      "findUnitForPath",
      "units",
    ], "Workspace catalog, source tree, and unit helpers. Does not include panelTree; use runtime.panelTree for panel-tree handles."),
    credentials: namespaceEntry([
      "store",
      "connect",
      "configureClient",
      "requestCredentialInput",
      "getClientConfigStatus",
      "deleteClientConfig",
      "listStoredCredentials",
      "revokeCredential",
      "grantCredential",
      "resolveCredential",
      "fetch",
      "hookForUrl",
      "gitHttp",
    ]),
    git: namespaceEntry([
      "http",
      "importProject",
      "completeWorkspaceDependencies",
      "setSharedRemote",
      "removeSharedRemote",
    ]),
    vcs: namespaceEntry([
      "applyEdits",
      "readFile",
      "listFiles",
      "revert",
      "status",
      "unitStatus",
      "log",
      "diff",
      "resolveHead",
      "merge",
      "abortMerge",
      "pendingMerge",
      "publishStatus",
      "publish",
      "recall",
    ]),
    gad: namespaceEntry([
      "rawSql",
      "query",
      "status",
      "ensureBlob",
      "getTrajectoryBranchHead",
      "appendTrajectoryBatch",
      "listTrajectoryEvents",
      "appendChannelEnvelope",
      "getChannelEnvelope",
      "getTrajectoryForEnvelope",
      "listPublishedEnvelopesForTrajectory",
      "getEnvelopesForTrajectory",
      "getPublishedArtifactsForTurn",
      "getPrivateLineageForPublishedEnvelope",
      "getDownstreamConsumers",
      "getChannelReplayWindow",
      "listChannelEnvelopesAfter",
      "listChannelEnvelopesBefore",
      "getInitialChannelWindow",
      "listChannelEnvelopes",
      "inspectChannelEnvelopes",
      "listStoredValueRefs",
      "inspectStorageDiagnostics",
      "listGadBranchFiles",
      "diffGadStates",
      "readGadFileAtState",
      "getGadStateProducer",
      "blameGadFileSnippet",
      "validateGadHashes",
      "clearDirtyAfterValidation",
      "checkGadIntegrity",
      "rebuildTrajectoryProjections",
    ]),
    webhooks: namespaceEntry([
      "createSubscription",
      "listSubscriptions",
      "revokeSubscription",
      "rotateSecret",
    ]),
    extensions: namespaceEntry(["use", "on", "list", "reload"]),
    approvals: namespaceEntry(["request", "revoke", "list"]),
    notifications: namespaceEntry(["show", "dismiss"]),
    contextId: valueEntry(),
    gatewayConfig: valueEntry("Gateway base URL and bearer token for NatStack service routes."),
    gatewayFetch: valueEntry(
      "Fetch helper that prefixes gateway-relative paths and adds Authorization: Bearer."
    ),
    callMain: valueEntry(),
    openExternal: valueEntry(),
    requestApproval: valueEntry(),
    revokeApproval: valueEntry(),
    listApprovals: valueEntry(),
    expose: valueEntry(),
    getParent: valueEntry(),
    panelTree: namespaceEntry(
      ["self", "get", "list", "roots", "children", "parent", "navigate", "open"],
      panelTreeDescription
    ),
    handleRpcPost: valueEntry(),
    destroy: valueEntry(),
  },
};
