// Types
export type {
  UIFileStatus,
  FileState,
  DiffState,
  CommitEntry,
  RefreshTrigger,
  GitStoreConfig,
  GitNotification,
  FileChange,
  FileDiff,
  StashEntry,
  GitClient,
  FsPromisesLike,
} from "./types";

// Core atoms
export {
  configAtom,
  filesAtom,
  diffsAtom,
  stashesAtom,
  commitsAtom,
  commitsHasMoreAtom,
  commitsDepthAtom,
  focusedSectionAtom,
  focusedIndexAtom,
  branchAtom,
  lastRefreshAtom,
  refreshingAtom,
  loadingAtom,
  errorAtom,
  stashLoadingAtom,
  stashActionLoadingAtom,
  stashErrorAtom,
  historyLoadingAtom,
  actionLoadingAtom,
  discardPathAtom,
  showUnstageConfirmAtom,
  dropStashIndexAtom,
  showCommitFormAtom,
  loadingDiffsAtom,
  diffErrorsAtom,
  blameCacheAtom,
  historyCacheAtom,
  allTrackedFilesAtom,
  headerMinimizedAtom,
  emptyDirectoriesAtom,
} from "./atoms";
export type { BlameCacheEntry, HistoryCacheEntry } from "./atoms";

// Selectors (derived atoms)
export {
  stagedFilesAtom,
  unstagedFilesAtom,
  changesTreeFilesAtom,
  partiallyStagedFilesAtom,
  hasStagedAtom,
  hasChangesAtom,
  pollingPausedAtom,
  focusedPathAtom,
  getDiffAtom,
  computeDiffStats,
} from "./selectors";

// Actions (write atoms)
export {
  refreshStatusAtom,
  manualRefreshAtom,
  refreshStashesAtom,
  refreshHistoryAtom,
  loadMoreHistoryAtom,
  stageFileAtom,
  stageHunksAtom,
  stageAllAtom,
  unstageFileAtom,
  unstageHunksAtom,
  unstageAllAtom,
  discardFileAtom,
  saveFileAtom,
  createFileAtom,
  deletePathAtom,
  commitAtom,
  createStashAtom,
  applyStashAtom,
  popStashAtom,
  dropStashAtom,
  fetchDiffAtom,
  clearDiffCacheAtom,
  setFocusedSectionAtom,
  moveFocusUpAtom,
  moveFocusDownAtom,
  toggleFocusedSectionAtom,
  initializeStoreAtom,
  cleanupStoreAtom,
} from "./actions";
